version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - hold:
          type: approval
          requires:
            - build

      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
              - hold

orbs:
  ruby: circleci/ruby@1.7.1


jobs:
  build:
    working_directory: ~/travelCalculator
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest . --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME
      - run:
          name: run-docker-image
          command: docker run -p 80:80 -d $IMAGE_NAME

  deploy:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export CONTAINER_NAME=\"$CONTAINER_NAME\"; export IMAGE_NAME=\"$IMAGE_NAME\"; rm -rf travelCalculator/; git clone https://github.com/Danod12/travelCalculator; source travelCalculator/deploy.sh"
